#!/bin/sh

if [ ! -e ~/.gitconfig ]; then
    if [ -n "$_CONF_DEV_GIT_NAME" ]; then

        printf '[user]\n' > ~/.gitconfig
        printf '\tname = %s\n' $_CONF_DEV_GIT_NAME >> ~/.gitconfig
        printf '\temail = %s\n' $_CONF_DEV_GIT_EMAIL >> ~/.gitconfig
    else
        _warn "Not configuring git as git settings were not provided"
    fi
else
    _warn "Git is already configured, bypassing"
fi
