#!/bin/sh

import git:install/time.sh

case $_SUB_PLATFORM in
    Ubuntu)
        case $_ARCHITECTURE in
            aarch64|arm64)
                _warn "Unsupported architecture, $_ARCHITECTURE"
                break
                ;;
        esac

        _detail "installing mockoon on $_ARCHITECTURE"
        _USE_SUDO=1 _timeout $_CONF_INSTALL_STEP_TIMEOUT "snap install mockoon" snap install mockoon
        ;;
    *)
        _warn "Unsupported distribution, $_SUB_PLATFORM"
        ;;
esac
