#!/bin/sh

import git:install/download.sh

if [ -n "$_INSTALLER" ]; then
	_warn "Using $_INSTALLER to install this package"
	return
fi

_VERSION=2.0.10
_download https://github.com/zyedidia/micro/releases/download/v$_VERSION/micro-$_VERSION-win64.zip micro.zip

unzip micro.zip

mv micro-$_VERSION/micro.exe $_INSTALL_BIN_PATH

