#!/bin/sh

import git:install/download.sh
import git:install/extract.sh

_DBEAVER_CONTENTS=$(mktemp -d)

_cleanup_dbeaver() {
	rm -rf $_DBEAVER_CONTENTS
}

_download https://dbeaver.io/files/dbeaver-ce-latest-linux.gtk.x86_64.tar.gz
_extract $_DOWNLOADED_FILE $_DBEAVER_CONTENTS
_defer _cleanup_dbeaver

$_SUDO_CMD mkdir -p $_CONF_INSTALL_APPLICATION_LIBRARY_PATH/feature/$_FEATURE_NAME
$_SUDO_CMD mv $_DBEAVER_CONTENTS/dbeaver/* $_CONF_INSTALL_APPLICATION_LIBRARY_PATH/feature/$_FEATURE_NAME
